name: tp1-escalabilidad
services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "15672:15672"  
      - "5672:5672"  

  server:
    build: ./server
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq

  client:
    build: ./client
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    volumes:
      - ./data:/client/data